name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/samplescript
          echo -e "echo sample" > .debpkg/usr/bin/samplescript
          chmod +x .debpkg/usr/bin/samplescript
          echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf
      - uses: jiro4989/build-deb-action@v2
        with:
          package: Ai-Icons
          package_root: .debpkg
          maintainer: peng1029
          version: 0.01
          arch: 'iphoneos-arm'
          depends: 'com.anemonetheming.anemone | com.spark.snowboard'
          desc: 'Ai App Icons generated my dall-e mini'
